service: help
runtime: python27
api_version: 1
threadsafe: true

# Default expiration is 10 minutes.
default_expiration: 1m

inbound_services:
- warmup

libraries:
- name: "setuptools"
  version: "0.6c11"

handlers:
- url: /
  static_files: site/index.html
  upload: site/index.html
  application_readable: true

# Consider anything matching a dot static content.
- url: /(.*\..*)
  static_files: site/\1
  upload: site/(.*\..*)
  application_readable: true

skip_files:
- ^\.git
- ^\.gitignore
- ^bower
- ^bower.json
- ^bower_components
- ^Gruntfile.js
- ^node_modules
- ^package.json
- ^venv
